/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Entity} from './Entity';
import {SyncPlatform} from './SyncPlatform';

/**
 * The AddOnOption model module.
 * @module model/AddOnOption
 * @version v1
 */
export class AddOnOption extends Entity {
  /**
   * Constructs a new <code>AddOnOption</code>.
   * @alias module:model/AddOnOption
   * @class
   * @extends module:model/Entity
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>AddOnOption</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AddOnOption} obj Optional instance to populate.
   * @return {module:model/AddOnOption} The populated <code>AddOnOption</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AddOnOption();
      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], 'Number');
      if (data.hasOwnProperty('addOnId'))
        obj.addOnId = ApiClient.convertToType(data['addOnId'], 'Number');
      if (data.hasOwnProperty('addOn'))
        obj.addOn = ApiClient.convertToType(data['addOn'], Object);
      if (data.hasOwnProperty('syncId'))
        obj.syncId = ApiClient.convertToType(data['syncId'], 'String');
      if (data.hasOwnProperty('lastSynced'))
        obj.lastSynced = ApiClient.convertToType(data['lastSynced'], 'Date');
      if (data.hasOwnProperty('syncPlatform'))
        obj.syncPlatform = SyncPlatform.constructFromObject(data['syncPlatform']);
    }
    return obj;
  }
}

/**
 * @member {Number} price
 */
AddOnOption.prototype.price = undefined;

/**
 * @member {Number} addOnId
 */
AddOnOption.prototype.addOnId = undefined;

/**
 * @member {Object} addOn
 */
AddOnOption.prototype.addOn = undefined;

/**
 * @member {String} syncId
 */
AddOnOption.prototype.syncId = undefined;

/**
 * @member {Date} lastSynced
 */
AddOnOption.prototype.lastSynced = undefined;

/**
 * @member {module:model/SyncPlatform} syncPlatform
 */
AddOnOption.prototype.syncPlatform = undefined;

