/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AddOnOption} from './AddOnOption';
import {Entity} from './Entity';
import {SyncPlatform} from './SyncPlatform';

/**
 * The AddOn model module.
 * @module model/AddOn
 * @version v1
 */
export class AddOn extends Entity {
  /**
   * Constructs a new <code>AddOn</code>.
   * @alias module:model/AddOn
   * @class
   * @extends module:model/Entity
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>AddOn</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AddOn} obj Optional instance to populate.
   * @return {module:model/AddOn} The populated <code>AddOn</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AddOn();
      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('addOnOptions'))
        obj.addOnOptions = ApiClient.convertToType(data['addOnOptions'], [AddOnOption]);
      if (data.hasOwnProperty('maximumAmount'))
        obj.maximumAmount = ApiClient.convertToType(data['maximumAmount'], 'Number');
      if (data.hasOwnProperty('optional'))
        obj.optional = ApiClient.convertToType(data['optional'], 'Boolean');
      if (data.hasOwnProperty('storeId'))
        obj.storeId = ApiClient.convertToType(data['storeId'], 'Number');
      if (data.hasOwnProperty('store'))
        obj.store = ApiClient.convertToType(data['store'], Object);
      if (data.hasOwnProperty('syncId'))
        obj.syncId = ApiClient.convertToType(data['syncId'], 'String');
      if (data.hasOwnProperty('lastSynced'))
        obj.lastSynced = ApiClient.convertToType(data['lastSynced'], 'Date');
      if (data.hasOwnProperty('syncPlatform'))
        obj.syncPlatform = SyncPlatform.constructFromObject(data['syncPlatform']);
    }
    return obj;
  }
}

/**
 * The AddOnOptions that are used by this Add On
 * @member {Array.<module:model/AddOnOption>} addOnOptions
 */
AddOn.prototype.addOnOptions = undefined;

/**
 * The Maximum Amount that a user can select.
 * @member {Number} maximumAmount
 */
AddOn.prototype.maximumAmount = undefined;

/**
 * @member {Boolean} optional
 */
AddOn.prototype.optional = undefined;

/**
 * @member {Number} storeId
 */
AddOn.prototype.storeId = undefined;

/**
 * @member {Object} store
 */
AddOn.prototype.store = undefined;

/**
 * @member {String} syncId
 */
AddOn.prototype.syncId = undefined;

/**
 * @member {Date} lastSynced
 */
AddOn.prototype.lastSynced = undefined;

/**
 * @member {module:model/SyncPlatform} syncPlatform
 */
AddOn.prototype.syncPlatform = undefined;

