/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AuthenticatorDetails model module.
 * @module model/AuthenticatorDetails
 * @version v1
 */
export class AuthenticatorDetails {
  /**
   * Constructs a new <code>AuthenticatorDetails</code>.
   * @alias module:model/AuthenticatorDetails
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AuthenticatorDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AuthenticatorDetails} obj Optional instance to populate.
   * @return {module:model/AuthenticatorDetails} The populated <code>AuthenticatorDetails</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AuthenticatorDetails();
      if (data.hasOwnProperty('sharedKey'))
        obj.sharedKey = ApiClient.convertToType(data['sharedKey'], 'String');
      if (data.hasOwnProperty('authenticatorUri'))
        obj.authenticatorUri = ApiClient.convertToType(data['authenticatorUri'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} sharedKey
 */
AuthenticatorDetails.prototype.sharedKey = undefined;

/**
 * @member {String} authenticatorUri
 */
AuthenticatorDetails.prototype.authenticatorUri = undefined;

