/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Entity} from './Entity';
import {MediaLink} from './MediaLink';
import {SyncPlatform} from './SyncPlatform';

/**
 * The Category model module.
 * @module model/Category
 * @version v1
 */
export class Category extends Entity {
  /**
   * Constructs a new <code>Category</code>.
   * @alias module:model/Category
   * @class
   * @extends module:model/Entity
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>Category</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Category} obj Optional instance to populate.
   * @return {module:model/Category} The populated <code>Category</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Category();
      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('taxCategoryId'))
        obj.taxCategoryId = ApiClient.convertToType(data['taxCategoryId'], 'Number');
      if (data.hasOwnProperty('parentId'))
        obj.parentId = ApiClient.convertToType(data['parentId'], 'Number');
      if (data.hasOwnProperty('storeId'))
        obj.storeId = ApiClient.convertToType(data['storeId'], 'Number');
      if (data.hasOwnProperty('store'))
        obj.store = ApiClient.convertToType(data['store'], Object);
      if (data.hasOwnProperty('isFeaturedItem'))
        obj.isFeaturedItem = ApiClient.convertToType(data['isFeaturedItem'], 'Boolean');
      if (data.hasOwnProperty('mediaLinks'))
        obj.mediaLinks = ApiClient.convertToType(data['mediaLinks'], [MediaLink]);
      if (data.hasOwnProperty('syncId'))
        obj.syncId = ApiClient.convertToType(data['syncId'], 'String');
      if (data.hasOwnProperty('lastSynced'))
        obj.lastSynced = ApiClient.convertToType(data['lastSynced'], 'Date');
      if (data.hasOwnProperty('syncPlatform'))
        obj.syncPlatform = SyncPlatform.constructFromObject(data['syncPlatform']);
    }
    return obj;
  }
}

/**
 * If the Tax Category is set the 
 * @member {Number} taxCategoryId
 */
Category.prototype.taxCategoryId = undefined;

/**
 * The ID of the Parent Category
 * @member {Number} parentId
 */
Category.prototype.parentId = undefined;

/**
 * The ID of the Store that the Category belongs to
 * @member {Number} storeId
 */
Category.prototype.storeId = undefined;

/**
 * The Store the Category belongs to
 * @member {Object} store
 */
Category.prototype.store = undefined;

/**
 * @member {Boolean} isFeaturedItem
 */
Category.prototype.isFeaturedItem = undefined;

/**
 * @member {Array.<module:model/MediaLink>} mediaLinks
 */
Category.prototype.mediaLinks = undefined;

/**
 * @member {String} syncId
 */
Category.prototype.syncId = undefined;

/**
 * @member {Date} lastSynced
 */
Category.prototype.lastSynced = undefined;

/**
 * @member {module:model/SyncPlatform} syncPlatform
 */
Category.prototype.syncPlatform = undefined;

