/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Entity} from './Entity';
import {MediaLink} from './MediaLink';

/**
 * The Charity model module.
 * @module model/Charity
 * @version v1
 */
export class Charity extends Entity {
  /**
   * Constructs a new <code>Charity</code>.
   * @alias module:model/Charity
   * @class
   * @extends module:model/Entity
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>Charity</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Charity} obj Optional instance to populate.
   * @return {module:model/Charity} The populated <code>Charity</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Charity();
      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('address'))
        obj.address = ApiClient.convertToType(data['address'], Object);
      if (data.hasOwnProperty('addressId'))
        obj.addressId = ApiClient.convertToType(data['addressId'], 'Number');
      if (data.hasOwnProperty('phoneNumber'))
        obj.phoneNumber = ApiClient.convertToType(data['phoneNumber'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('country'))
        obj.country = ApiClient.convertToType(data['country'], 'String');
      if (data.hasOwnProperty('registrationNo'))
        obj.registrationNo = ApiClient.convertToType(data['registrationNo'], 'String');
      if (data.hasOwnProperty('website'))
        obj.website = ApiClient.convertToType(data['website'], 'String');
      if (data.hasOwnProperty('mediaLinks'))
        obj.mediaLinks = ApiClient.convertToType(data['mediaLinks'], [MediaLink]);
      if (data.hasOwnProperty('facebook'))
        obj.facebook = ApiClient.convertToType(data['facebook'], 'String');
      if (data.hasOwnProperty('instagram'))
        obj.instagram = ApiClient.convertToType(data['instagram'], 'String');
      if (data.hasOwnProperty('twitter'))
        obj.twitter = ApiClient.convertToType(data['twitter'], 'String');
      if (data.hasOwnProperty('youtube'))
        obj.youtube = ApiClient.convertToType(data['youtube'], 'String');
      if (data.hasOwnProperty('pinterest'))
        obj.pinterest = ApiClient.convertToType(data['pinterest'], 'String');
      if (data.hasOwnProperty('messenger'))
        obj.messenger = ApiClient.convertToType(data['messenger'], 'String');
      if (data.hasOwnProperty('telegram'))
        obj.telegram = ApiClient.convertToType(data['telegram'], 'String');
      if (data.hasOwnProperty('line'))
        obj.line = ApiClient.convertToType(data['line'], 'String');
      if (data.hasOwnProperty('skype'))
        obj.skype = ApiClient.convertToType(data['skype'], 'String');
      if (data.hasOwnProperty('whatsapp'))
        obj.whatsapp = ApiClient.convertToType(data['whatsapp'], 'String');
      if (data.hasOwnProperty('wechat'))
        obj.wechat = ApiClient.convertToType(data['wechat'], 'String');
      if (data.hasOwnProperty('verificationId'))
        obj.verificationId = ApiClient.convertToType(data['verificationId'], 'Number');
      if (data.hasOwnProperty('verification'))
        obj.verification = ApiClient.convertToType(data['verification'], Object);
      if (data.hasOwnProperty('bankId'))
        obj.bankId = ApiClient.convertToType(data['bankId'], 'Number');
      if (data.hasOwnProperty('bank'))
        obj.bank = ApiClient.convertToType(data['bank'], Object);
      if (data.hasOwnProperty('bankAccountNumber'))
        obj.bankAccountNumber = ApiClient.convertToType(data['bankAccountNumber'], 'String');
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} description
 */
Charity.prototype.description = undefined;

/**
 * @member {Object} address
 */
Charity.prototype.address = undefined;

/**
 * @member {Number} addressId
 */
Charity.prototype.addressId = undefined;

/**
 * @member {String} phoneNumber
 */
Charity.prototype.phoneNumber = undefined;

/**
 * @member {String} email
 */
Charity.prototype.email = undefined;

/**
 * @member {String} country
 */
Charity.prototype.country = undefined;

/**
 * @member {String} registrationNo
 */
Charity.prototype.registrationNo = undefined;

/**
 * @member {String} website
 */
Charity.prototype.website = undefined;

/**
 * @member {Array.<module:model/MediaLink>} mediaLinks
 */
Charity.prototype.mediaLinks = undefined;

/**
 * @member {String} facebook
 */
Charity.prototype.facebook = undefined;

/**
 * @member {String} instagram
 */
Charity.prototype.instagram = undefined;

/**
 * @member {String} twitter
 */
Charity.prototype.twitter = undefined;

/**
 * @member {String} youtube
 */
Charity.prototype.youtube = undefined;

/**
 * @member {String} pinterest
 */
Charity.prototype.pinterest = undefined;

/**
 * @member {String} messenger
 */
Charity.prototype.messenger = undefined;

/**
 * @member {String} telegram
 */
Charity.prototype.telegram = undefined;

/**
 * @member {String} line
 */
Charity.prototype.line = undefined;

/**
 * @member {String} skype
 */
Charity.prototype.skype = undefined;

/**
 * @member {String} whatsapp
 */
Charity.prototype.whatsapp = undefined;

/**
 * @member {String} wechat
 */
Charity.prototype.wechat = undefined;

/**
 * @member {Number} verificationId
 */
Charity.prototype.verificationId = undefined;

/**
 * @member {Object} verification
 */
Charity.prototype.verification = undefined;

/**
 * @member {Number} bankId
 */
Charity.prototype.bankId = undefined;

/**
 * @member {Object} bank
 */
Charity.prototype.bank = undefined;

/**
 * @member {String} bankAccountNumber
 */
Charity.prototype.bankAccountNumber = undefined;

/**
 * @member {String} userId
 */
Charity.prototype.userId = undefined;

