/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PaymentMethod} from './PaymentMethod';
import {ShippingMethod} from './ShippingMethod';

/**
 * The CheckoutApiRequest model module.
 * @module model/CheckoutApiRequest
 * @version v1
 */
export class CheckoutApiRequest {
  /**
   * Constructs a new <code>CheckoutApiRequest</code>.
   * @alias module:model/CheckoutApiRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CheckoutApiRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CheckoutApiRequest} obj Optional instance to populate.
   * @return {module:model/CheckoutApiRequest} The populated <code>CheckoutApiRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CheckoutApiRequest();
      if (data.hasOwnProperty('shipmentAddressId'))
        obj.shipmentAddressId = ApiClient.convertToType(data['shipmentAddressId'], 'Number');
      if (data.hasOwnProperty('shippingMethodCost'))
        obj.shippingMethodCost = ApiClient.convertToType(data['shippingMethodCost'], 'Number');
      if (data.hasOwnProperty('shippingMethod'))
        obj.shippingMethod = ShippingMethod.constructFromObject(data['shippingMethod']);
      if (data.hasOwnProperty('shippingNote'))
        obj.shippingNote = ApiClient.convertToType(data['shippingNote'], 'String');
      if (data.hasOwnProperty('paymentMethod'))
        obj.paymentMethod = PaymentMethod.constructFromObject(data['paymentMethod']);
      if (data.hasOwnProperty('shippingMethodService'))
        obj.shippingMethodService = ApiClient.convertToType(data['shippingMethodService'], 'String');
      if (data.hasOwnProperty('storeId'))
        obj.storeId = ApiClient.convertToType(data['storeId'], 'Number');
      if (data.hasOwnProperty('cutlery'))
        obj.cutlery = ApiClient.convertToType(data['cutlery'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Number} shipmentAddressId
 */
CheckoutApiRequest.prototype.shipmentAddressId = undefined;

/**
 * @member {Number} shippingMethodCost
 */
CheckoutApiRequest.prototype.shippingMethodCost = undefined;

/**
 * @member {module:model/ShippingMethod} shippingMethod
 */
CheckoutApiRequest.prototype.shippingMethod = undefined;

/**
 * @member {String} shippingNote
 */
CheckoutApiRequest.prototype.shippingNote = undefined;

/**
 * @member {module:model/PaymentMethod} paymentMethod
 */
CheckoutApiRequest.prototype.paymentMethod = undefined;

/**
 * @member {String} shippingMethodService
 */
CheckoutApiRequest.prototype.shippingMethodService = undefined;

/**
 * @member {Number} storeId
 */
CheckoutApiRequest.prototype.storeId = undefined;

/**
 * @member {Boolean} cutlery
 */
CheckoutApiRequest.prototype.cutlery = undefined;

