/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Entity} from './Entity';

/**
 * The DeliveryPartner model module.
 * @module model/DeliveryPartner
 * @version v1
 */
export class DeliveryPartner extends Entity {
  /**
   * Constructs a new <code>DeliveryPartner</code>.
   * @alias module:model/DeliveryPartner
   * @class
   * @extends module:model/Entity
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>DeliveryPartner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeliveryPartner} obj Optional instance to populate.
   * @return {module:model/DeliveryPartner} The populated <code>DeliveryPartner</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeliveryPartner();
      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('isPublic'))
        obj.isPublic = ApiClient.convertToType(data['isPublic'], 'Boolean');
      if (data.hasOwnProperty('contactName'))
        obj.contactName = ApiClient.convertToType(data['contactName'], 'String');
      if (data.hasOwnProperty('phoneNumber'))
        obj.phoneNumber = ApiClient.convertToType(data['phoneNumber'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('website'))
        obj.website = ApiClient.convertToType(data['website'], 'String');
      if (data.hasOwnProperty('driverCount'))
        obj.driverCount = ApiClient.convertToType(data['driverCount'], 'Number');
      if (data.hasOwnProperty('offline'))
        obj.offline = ApiClient.convertToType(data['offline'], 'Boolean');
      if (data.hasOwnProperty('coverageArea'))
        obj.coverageArea = ApiClient.convertToType(data['coverageArea'], 'String');
      if (data.hasOwnProperty('addressId'))
        obj.addressId = ApiClient.convertToType(data['addressId'], 'Number');
      if (data.hasOwnProperty('address'))
        obj.address = ApiClient.convertToType(data['address'], Object);
      if (data.hasOwnProperty('facebook'))
        obj.facebook = ApiClient.convertToType(data['facebook'], 'String');
      if (data.hasOwnProperty('isExpress'))
        obj.isExpress = ApiClient.convertToType(data['isExpress'], 'Boolean');
      if (data.hasOwnProperty('canDeliverFood'))
        obj.canDeliverFood = ApiClient.convertToType(data['canDeliverFood'], 'Boolean');
      if (data.hasOwnProperty('isBusiness'))
        obj.isBusiness = ApiClient.convertToType(data['isBusiness'], 'Boolean');
      if (data.hasOwnProperty('mrzData'))
        obj.mrzData = ApiClient.convertToType(data['mrzData'], 'Blob');
      if (data.hasOwnProperty('logoData'))
        obj.logoData = ApiClient.convertToType(data['logoData'], 'Blob');
      if (data.hasOwnProperty('businessRegistrationData'))
        obj.businessRegistrationData = ApiClient.convertToType(data['businessRegistrationData'], 'Blob');
      if (data.hasOwnProperty('taxRegistrationData'))
        obj.taxRegistrationData = ApiClient.convertToType(data['taxRegistrationData'], 'Blob');
      if (data.hasOwnProperty('logoContentType'))
        obj.logoContentType = ApiClient.convertToType(data['logoContentType'], 'String');
      if (data.hasOwnProperty('mrzDataContentType'))
        obj.mrzDataContentType = ApiClient.convertToType(data['mrzDataContentType'], 'String');
      if (data.hasOwnProperty('businessRegistrationDataContentType'))
        obj.businessRegistrationDataContentType = ApiClient.convertToType(data['businessRegistrationDataContentType'], 'String');
      if (data.hasOwnProperty('taxRegistrationDataContentType'))
        obj.taxRegistrationDataContentType = ApiClient.convertToType(data['taxRegistrationDataContentType'], 'String');
      if (data.hasOwnProperty('verificationId'))
        obj.verificationId = ApiClient.convertToType(data['verificationId'], 'Number');
      if (data.hasOwnProperty('verification'))
        obj.verification = ApiClient.convertToType(data['verification'], Object);
    }
    return obj;
  }
}

/**
 * @member {Boolean} isPublic
 */
DeliveryPartner.prototype.isPublic = undefined;

/**
 * @member {String} contactName
 */
DeliveryPartner.prototype.contactName = undefined;

/**
 * @member {String} phoneNumber
 */
DeliveryPartner.prototype.phoneNumber = undefined;

/**
 * @member {String} email
 */
DeliveryPartner.prototype.email = undefined;

/**
 * @member {String} website
 */
DeliveryPartner.prototype.website = undefined;

/**
 * @member {Number} driverCount
 */
DeliveryPartner.prototype.driverCount = undefined;

/**
 * @member {Boolean} offline
 */
DeliveryPartner.prototype.offline = undefined;

/**
 * @member {String} coverageArea
 */
DeliveryPartner.prototype.coverageArea = undefined;

/**
 * @member {Number} addressId
 */
DeliveryPartner.prototype.addressId = undefined;

/**
 * @member {Object} address
 */
DeliveryPartner.prototype.address = undefined;

/**
 * @member {String} facebook
 */
DeliveryPartner.prototype.facebook = undefined;

/**
 * @member {Boolean} isExpress
 */
DeliveryPartner.prototype.isExpress = undefined;

/**
 * @member {Boolean} canDeliverFood
 */
DeliveryPartner.prototype.canDeliverFood = undefined;

/**
 * @member {Boolean} isBusiness
 */
DeliveryPartner.prototype.isBusiness = undefined;

/**
 * @member {Blob} mrzData
 */
DeliveryPartner.prototype.mrzData = undefined;

/**
 * @member {Blob} logoData
 */
DeliveryPartner.prototype.logoData = undefined;

/**
 * @member {Blob} businessRegistrationData
 */
DeliveryPartner.prototype.businessRegistrationData = undefined;

/**
 * @member {Blob} taxRegistrationData
 */
DeliveryPartner.prototype.taxRegistrationData = undefined;

/**
 * @member {String} logoContentType
 */
DeliveryPartner.prototype.logoContentType = undefined;

/**
 * @member {String} mrzDataContentType
 */
DeliveryPartner.prototype.mrzDataContentType = undefined;

/**
 * @member {String} businessRegistrationDataContentType
 */
DeliveryPartner.prototype.businessRegistrationDataContentType = undefined;

/**
 * @member {String} taxRegistrationDataContentType
 */
DeliveryPartner.prototype.taxRegistrationDataContentType = undefined;

/**
 * @member {Number} verificationId
 */
DeliveryPartner.prototype.verificationId = undefined;

/**
 * @member {Object} verification
 */
DeliveryPartner.prototype.verification = undefined;

