/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The EnableDisableTwoFactorAuthenticationResponse model module.
 * @module model/EnableDisableTwoFactorAuthenticationResponse
 * @version v1
 */
export class EnableDisableTwoFactorAuthenticationResponse {
  /**
   * Constructs a new <code>EnableDisableTwoFactorAuthenticationResponse</code>.
   * @alias module:model/EnableDisableTwoFactorAuthenticationResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>EnableDisableTwoFactorAuthenticationResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EnableDisableTwoFactorAuthenticationResponse} obj Optional instance to populate.
   * @return {module:model/EnableDisableTwoFactorAuthenticationResponse} The populated <code>EnableDisableTwoFactorAuthenticationResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EnableDisableTwoFactorAuthenticationResponse();
      if (data.hasOwnProperty('recoveryCodes'))
        obj.recoveryCodes = ApiClient.convertToType(data['recoveryCodes'], ['String']);
      if (data.hasOwnProperty('twoFactorEnabled'))
        obj.twoFactorEnabled = ApiClient.convertToType(data['twoFactorEnabled'], 'Boolean');
      if (data.hasOwnProperty('is2faTokenValid'))
        obj.is2faTokenValid = ApiClient.convertToType(data['is2faTokenValid'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} recoveryCodes
 */
EnableDisableTwoFactorAuthenticationResponse.prototype.recoveryCodes = undefined;

/**
 * @member {Boolean} twoFactorEnabled
 */
EnableDisableTwoFactorAuthenticationResponse.prototype.twoFactorEnabled = undefined;

/**
 * @member {Boolean} is2faTokenValid
 */
EnableDisableTwoFactorAuthenticationResponse.prototype.is2faTokenValid = undefined;

