/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Entity model module.
 * @module model/Entity
 * @version v1
 */
export class Entity {
  /**
   * Constructs a new <code>Entity</code>.
   * Base Entity
   * @alias module:model/Entity
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Entity</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Entity} obj Optional instance to populate.
   * @return {module:model/Entity} The populated <code>Entity</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Entity();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('tenantId'))
        obj.tenantId = ApiClient.convertToType(data['tenantId'], 'Number');
      if (data.hasOwnProperty('tenant'))
        obj.tenant = ApiClient.convertToType(data['tenant'], Object);
      if (data.hasOwnProperty('createdBy'))
        obj.createdBy = ApiClient.convertToType(data['createdBy'], 'String');
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
      if (data.hasOwnProperty('updatedBy'))
        obj.updatedBy = ApiClient.convertToType(data['updatedBy'], 'String');
      if (data.hasOwnProperty('isDeleted'))
        obj.isDeleted = ApiClient.convertToType(data['isDeleted'], 'Boolean');
    }
    return obj;
  }
}

/**
 * The ID of the Entity
 * @member {Number} id
 */
Entity.prototype.id = undefined;

/**
 * The name used to display the entity
 * @member {String} name
 */
Entity.prototype.name = undefined;

/**
 * The ID of the Tenant this Entity belongs to
 * @member {Number} tenantId
 */
Entity.prototype.tenantId = undefined;

/**
 * The Tenant this entity belongs to
 * @member {Object} tenant
 */
Entity.prototype.tenant = undefined;

/**
 * ID of the User that created this entity
 * @member {String} createdBy
 */
Entity.prototype.createdBy = undefined;

/**
 * The Date/Time this Entity was Created
 * @member {Date} created
 */
Entity.prototype.created = undefined;

/**
 * The Date/Time this entity was Updated
 * @member {Date} updated
 */
Entity.prototype.updated = undefined;

/**
 * The ID of the User which updated this entity
 * @member {String} updatedBy
 */
Entity.prototype.updatedBy = undefined;

/**
 * Marks if the Entity is Deleted
 * @member {Boolean} isDeleted
 */
Entity.prototype.isDeleted = undefined;

