/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The KessApiResponseOfOrderData model module.
 * @module model/KessApiResponseOfOrderData
 * @version v1
 */
export class KessApiResponseOfOrderData {
  /**
   * Constructs a new <code>KessApiResponseOfOrderData</code>.
   * @alias module:model/KessApiResponseOfOrderData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>KessApiResponseOfOrderData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/KessApiResponseOfOrderData} obj Optional instance to populate.
   * @return {module:model/KessApiResponseOfOrderData} The populated <code>KessApiResponseOfOrderData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new KessApiResponseOfOrderData();
      if (data.hasOwnProperty('success'))
        obj.success = ApiClient.convertToType(data['success'], 'String');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], Object);
    }
    return obj;
  }
}

/**
 * @member {String} success
 */
KessApiResponseOfOrderData.prototype.success = undefined;

/**
 * @member {Object} data
 */
KessApiResponseOfOrderData.prototype.data = undefined;

