/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The KHQRResponseStatusOfKHQRData model module.
 * @module model/KHQRResponseStatusOfKHQRData
 * @version v1
 */
export class KHQRResponseStatusOfKHQRData {
  /**
   * Constructs a new <code>KHQRResponseStatusOfKHQRData</code>.
   * @alias module:model/KHQRResponseStatusOfKHQRData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>KHQRResponseStatusOfKHQRData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/KHQRResponseStatusOfKHQRData} obj Optional instance to populate.
   * @return {module:model/KHQRResponseStatusOfKHQRData} The populated <code>KHQRResponseStatusOfKHQRData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new KHQRResponseStatusOfKHQRData();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'Number');
      if (data.hasOwnProperty('errorCode'))
        obj.errorCode = ApiClient.convertToType(data['errorCode'], 'Number');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} code
 */
KHQRResponseStatusOfKHQRData.prototype.code = undefined;

/**
 * @member {Number} errorCode
 */
KHQRResponseStatusOfKHQRData.prototype.errorCode = undefined;

/**
 * @member {String} message
 */
KHQRResponseStatusOfKHQRData.prototype.message = undefined;

// Implement OneOfKHQRResponseOfKHQRDataStatus interface:
