/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The KHQRResponseOfKHQRData model module.
 * @module model/KHQRResponseOfKHQRData
 * @version v1
 */
export class KHQRResponseOfKHQRData {
  /**
   * Constructs a new <code>KHQRResponseOfKHQRData</code>.
   * @alias module:model/KHQRResponseOfKHQRData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>KHQRResponseOfKHQRData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/KHQRResponseOfKHQRData} obj Optional instance to populate.
   * @return {module:model/KHQRResponseOfKHQRData} The populated <code>KHQRResponseOfKHQRData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new KHQRResponseOfKHQRData();
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], Object);
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} status
 */
KHQRResponseOfKHQRData.prototype.status = undefined;

/**
 * @member {Object} data
 */
KHQRResponseOfKHQRData.prototype.data = undefined;

