/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Entity} from './Entity';

/**
 * The Language model module.
 * @module model/Language
 * @version v1
 */
export class Language extends Entity {
  /**
   * Constructs a new <code>Language</code>.
   * @alias module:model/Language
   * @class
   * @extends module:model/Entity
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>Language</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Language} obj Optional instance to populate.
   * @return {module:model/Language} The populated <code>Language</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Language();
      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('culture'))
        obj.culture = ApiClient.convertToType(data['culture'], 'String');
    }
    return obj;
  }
}

/**
 * The Culture Name
 * @member {String} culture
 */
Language.prototype.culture = undefined;

