/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Entity} from './Entity';

/**
 * The MediaLink model module.
 * @module model/MediaLink
 * @version v1
 */
export class MediaLink extends Entity {
  /**
   * Constructs a new <code>MediaLink</code>.
   * @alias module:model/MediaLink
   * @class
   * @extends module:model/Entity
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>MediaLink</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MediaLink} obj Optional instance to populate.
   * @return {module:model/MediaLink} The populated <code>MediaLink</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MediaLink();
      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('mediaId'))
        obj.mediaId = ApiClient.convertToType(data['mediaId'], 'Number');
      if (data.hasOwnProperty('media'))
        obj.media = ApiClient.convertToType(data['media'], Object);
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('entityId'))
        obj.entityId = ApiClient.convertToType(data['entityId'], 'Number');
      if (data.hasOwnProperty('entityType'))
        obj.entityType = ApiClient.convertToType(data['entityType'], 'String');
    }
    return obj;
  }
}

/**
 * The ID of the Media File
 * @member {Number} mediaId
 */
MediaLink.prototype.mediaId = undefined;

/**
 * The Media File
 * @member {Object} media
 */
MediaLink.prototype.media = undefined;

/**
 * The URL used to access the Media File
 * @member {String} url
 */
MediaLink.prototype.url = undefined;

/**
 * ID of the Entity this link refers to
 * @member {Number} entityId
 */
MediaLink.prototype.entityId = undefined;

/**
 * Type of the Entity this link refers to
 * @member {String} entityType
 */
MediaLink.prototype.entityType = undefined;

