/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MerchantStoreDashboard model module.
 * @module model/MerchantStoreDashboard
 * @version v1
 */
export class MerchantStoreDashboard {
  /**
   * Constructs a new <code>MerchantStoreDashboard</code>.
   * @alias module:model/MerchantStoreDashboard
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MerchantStoreDashboard</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MerchantStoreDashboard} obj Optional instance to populate.
   * @return {module:model/MerchantStoreDashboard} The populated <code>MerchantStoreDashboard</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MerchantStoreDashboard();
      if (data.hasOwnProperty('totalOrders'))
        obj.totalOrders = ApiClient.convertToType(data['totalOrders'], 'Number');
      if (data.hasOwnProperty('subscription'))
        obj.subscription = ApiClient.convertToType(data['subscription'], Object);
      if (data.hasOwnProperty('availableBalance'))
        obj.availableBalance = ApiClient.convertToType(data['availableBalance'], 'Number');
      if (data.hasOwnProperty('inventory'))
        obj.inventory = ApiClient.convertToType(data['inventory'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} totalOrders
 */
MerchantStoreDashboard.prototype.totalOrders = undefined;

/**
 * @member {Object} subscription
 */
MerchantStoreDashboard.prototype.subscription = undefined;

/**
 * @member {Number} availableBalance
 */
MerchantStoreDashboard.prototype.availableBalance = undefined;

/**
 * @member {Number} inventory
 */
MerchantStoreDashboard.prototype.inventory = undefined;

