/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MerchantProductsDashboard model module.
 * @module model/MerchantProductsDashboard
 * @version v1
 */
export class MerchantProductsDashboard {
  /**
   * Constructs a new <code>MerchantProductsDashboard</code>.
   * @alias module:model/MerchantProductsDashboard
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MerchantProductsDashboard</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MerchantProductsDashboard} obj Optional instance to populate.
   * @return {module:model/MerchantProductsDashboard} The populated <code>MerchantProductsDashboard</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MerchantProductsDashboard();
      if (data.hasOwnProperty('productsInStock'))
        obj.productsInStock = ApiClient.convertToType(data['productsInStock'], 'Number');
      if (data.hasOwnProperty('productsOutOfStock'))
        obj.productsOutOfStock = ApiClient.convertToType(data['productsOutOfStock'], 'Number');
      if (data.hasOwnProperty('productCategories'))
        obj.productCategories = ApiClient.convertToType(data['productCategories'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} productsInStock
 */
MerchantProductsDashboard.prototype.productsInStock = undefined;

/**
 * @member {Number} productsOutOfStock
 */
MerchantProductsDashboard.prototype.productsOutOfStock = undefined;

/**
 * @member {Number} productCategories
 */
MerchantProductsDashboard.prototype.productCategories = undefined;

