/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The OneOfMerchantStoreDashboardSubscription model module.
 * @module model/OneOfMerchantStoreDashboardSubscription
 * @version v1
 */
export class OneOfMerchantStoreDashboardSubscription {
  /**
   * Constructs a new <code>OneOfMerchantStoreDashboardSubscription</code>.
   * @alias module:model/OneOfMerchantStoreDashboardSubscription
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OneOfMerchantStoreDashboardSubscription</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OneOfMerchantStoreDashboardSubscription} obj Optional instance to populate.
   * @return {module:model/OneOfMerchantStoreDashboardSubscription} The populated <code>OneOfMerchantStoreDashboardSubscription</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OneOfMerchantStoreDashboardSubscription();
    }
    return obj;
  }
}
