/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {DayOfWeek} from './DayOfWeek';
import {Entity} from './Entity';

/**
 * The OpeningHour model module.
 * @module model/OpeningHour
 * @version v1
 */
export class OpeningHour extends Entity {
  /**
   * Constructs a new <code>OpeningHour</code>.
   * @alias module:model/OpeningHour
   * @class
   * @extends module:model/Entity
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>OpeningHour</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OpeningHour} obj Optional instance to populate.
   * @return {module:model/OpeningHour} The populated <code>OpeningHour</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OpeningHour();
      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('day'))
        obj.day = DayOfWeek.constructFromObject(data['day']);
      if (data.hasOwnProperty('openHour'))
        obj.openHour = ApiClient.convertToType(data['openHour'], 'Number');
      if (data.hasOwnProperty('openMinute'))
        obj.openMinute = ApiClient.convertToType(data['openMinute'], 'Number');
      if (data.hasOwnProperty('closeHour'))
        obj.closeHour = ApiClient.convertToType(data['closeHour'], 'Number');
      if (data.hasOwnProperty('closeMinute'))
        obj.closeMinute = ApiClient.convertToType(data['closeMinute'], 'Number');
      if (data.hasOwnProperty('storeId'))
        obj.storeId = ApiClient.convertToType(data['storeId'], 'Number');
      if (data.hasOwnProperty('store'))
        obj.store = ApiClient.convertToType(data['store'], Object);
    }
    return obj;
  }
}

/**
 * @member {module:model/DayOfWeek} day
 */
OpeningHour.prototype.day = undefined;

/**
 * @member {Number} openHour
 */
OpeningHour.prototype.openHour = undefined;

/**
 * @member {Number} openMinute
 */
OpeningHour.prototype.openMinute = undefined;

/**
 * @member {Number} closeHour
 */
OpeningHour.prototype.closeHour = undefined;

/**
 * @member {Number} closeMinute
 */
OpeningHour.prototype.closeMinute = undefined;

/**
 * @member {Number} storeId
 */
OpeningHour.prototype.storeId = undefined;

/**
 * @member {Object} store
 */
OpeningHour.prototype.store = undefined;

