/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Entity} from './Entity';

/**
 * The OrderItemAddOn model module.
 * @module model/OrderItemAddOn
 * @version v1
 */
export class OrderItemAddOn extends Entity {
  /**
   * Constructs a new <code>OrderItemAddOn</code>.
   * @alias module:model/OrderItemAddOn
   * @class
   * @extends module:model/Entity
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>OrderItemAddOn</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderItemAddOn} obj Optional instance to populate.
   * @return {module:model/OrderItemAddOn} The populated <code>OrderItemAddOn</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderItemAddOn();
      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('orderItem'))
        obj.orderItem = ApiClient.convertToType(data['orderItem'], Object);
      if (data.hasOwnProperty('orderItemId'))
        obj.orderItemId = ApiClient.convertToType(data['orderItemId'], 'Number');
      if (data.hasOwnProperty('addOnOptionId'))
        obj.addOnOptionId = ApiClient.convertToType(data['addOnOptionId'], 'Number');
      if (data.hasOwnProperty('addOnOption'))
        obj.addOnOption = ApiClient.convertToType(data['addOnOption'], Object);
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'Number');
      if (data.hasOwnProperty('instruction'))
        obj.instruction = ApiClient.convertToType(data['instruction'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Object} orderItem
 */
OrderItemAddOn.prototype.orderItem = undefined;

/**
 * @member {Number} orderItemId
 */
OrderItemAddOn.prototype.orderItemId = undefined;

/**
 * @member {Number} addOnOptionId
 */
OrderItemAddOn.prototype.addOnOptionId = undefined;

/**
 * @member {Object} addOnOption
 */
OrderItemAddOn.prototype.addOnOption = undefined;

/**
 * @member {Number} quantity
 */
OrderItemAddOn.prototype.quantity = undefined;

/**
 * @member {String} instruction
 */
OrderItemAddOn.prototype.instruction = undefined;

