/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {OrderDetail} from './OrderDetail';

/**
 * The OrderData model module.
 * @module model/OrderData
 * @version v1
 */
export class OrderData {
  /**
   * Constructs a new <code>OrderData</code>.
   * @alias module:model/OrderData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OrderData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderData} obj Optional instance to populate.
   * @return {module:model/OrderData} The populated <code>OrderData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderData();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('mch_id'))
        obj.mchId = ApiClient.convertToType(data['mch_id'], 'String');
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], 'String');
      if (data.hasOwnProperty('out_trade_no'))
        obj.outTradeNo = ApiClient.convertToType(data['out_trade_no'], 'String');
      if (data.hasOwnProperty('transaction_id'))
        obj.transactionId = ApiClient.convertToType(data['transaction_id'], Object);
      if (data.hasOwnProperty('token'))
        obj.token = ApiClient.convertToType(data['token'], 'String');
      if (data.hasOwnProperty('body'))
        obj.body = ApiClient.convertToType(data['body'], 'String');
      if (data.hasOwnProperty('total_amount'))
        obj.totalAmount = ApiClient.convertToType(data['total_amount'], 'String');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('seller_id'))
        obj.sellerId = ApiClient.convertToType(data['seller_id'], 'String');
      if (data.hasOwnProperty('notify_url'))
        obj.notifyUrl = ApiClient.convertToType(data['notify_url'], 'String');
      if (data.hasOwnProperty('detail'))
        obj.detail = ApiClient.convertToType(data['detail'], [OrderDetail]);
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'String');
      if (data.hasOwnProperty('updated_at'))
        obj.updatedAt = ApiClient.convertToType(data['updated_at'], 'Date');
      if (data.hasOwnProperty('payment_link'))
        obj.paymentLink = ApiClient.convertToType(data['payment_link'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
OrderData.prototype.id = undefined;

/**
 * @member {String} mchId
 */
OrderData.prototype.mchId = undefined;

/**
 * @member {String} userId
 */
OrderData.prototype.userId = undefined;

/**
 * @member {String} outTradeNo
 */
OrderData.prototype.outTradeNo = undefined;

/**
 * @member {Object} transactionId
 */
OrderData.prototype.transactionId = undefined;

/**
 * @member {String} token
 */
OrderData.prototype.token = undefined;

/**
 * @member {String} body
 */
OrderData.prototype.body = undefined;

/**
 * @member {String} totalAmount
 */
OrderData.prototype.totalAmount = undefined;

/**
 * @member {String} currency
 */
OrderData.prototype.currency = undefined;

/**
 * @member {String} status
 */
OrderData.prototype.status = undefined;

/**
 * @member {String} sellerId
 */
OrderData.prototype.sellerId = undefined;

/**
 * @member {String} notifyUrl
 */
OrderData.prototype.notifyUrl = undefined;

/**
 * @member {Array.<module:model/OrderDetail>} detail
 */
OrderData.prototype.detail = undefined;

/**
 * @member {String} createdAt
 */
OrderData.prototype.createdAt = undefined;

/**
 * @member {Date} updatedAt
 */
OrderData.prototype.updatedAt = undefined;

/**
 * @member {String} paymentLink
 */
OrderData.prototype.paymentLink = undefined;

// Implement OneOfKessApiResponseOfOrderDataData interface:
