/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The OrderDetail model module.
 * @module model/OrderDetail
 * @version v1
 */
export class OrderDetail {
  /**
   * Constructs a new <code>OrderDetail</code>.
   * @alias module:model/OrderDetail
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OrderDetail</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderDetail} obj Optional instance to populate.
   * @return {module:model/OrderDetail} The populated <code>OrderDetail</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderDetail();
      if (data.hasOwnProperty('no'))
        obj.no = ApiClient.convertToType(data['no'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], 'String');
      if (data.hasOwnProperty('qty'))
        obj.qty = ApiClient.convertToType(data['qty'], 'String');
      if (data.hasOwnProperty('discount'))
        obj.discount = ApiClient.convertToType(data['discount'], 'Number');
    }
    return obj;
  }
}

/**
 * Product ID.
 * @member {String} no
 */
OrderDetail.prototype.no = undefined;

/**
 * Product Name
 * @member {String} name
 */
OrderDetail.prototype.name = undefined;

/**
 * Unit price
 * @member {String} price
 */
OrderDetail.prototype.price = undefined;

/**
 * Unit quantity
 * @member {String} qty
 */
OrderDetail.prototype.qty = undefined;

/**
 * Unit discount
 * @member {Number} discount
 */
OrderDetail.prototype.discount = undefined;

