/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Entity} from './Entity';

/**
 * The ProductVariantType model module.
 * @module model/ProductVariantType
 * @version v1
 */
export class ProductVariantType extends Entity {
  /**
   * Constructs a new <code>ProductVariantType</code>.
   * @alias module:model/ProductVariantType
   * @class
   * @extends module:model/Entity
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>ProductVariantType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductVariantType} obj Optional instance to populate.
   * @return {module:model/ProductVariantType} The populated <code>ProductVariantType</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductVariantType();
      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('product'))
        obj.product = ApiClient.convertToType(data['product'], Object);
      if (data.hasOwnProperty('productId'))
        obj.productId = ApiClient.convertToType(data['productId'], 'Number');
      if (data.hasOwnProperty('variantType'))
        obj.variantType = ApiClient.convertToType(data['variantType'], Object);
      if (data.hasOwnProperty('variantTypeId'))
        obj.variantTypeId = ApiClient.convertToType(data['variantTypeId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Object} product
 */
ProductVariantType.prototype.product = undefined;

/**
 * @member {Number} productId
 */
ProductVariantType.prototype.productId = undefined;

/**
 * @member {Object} variantType
 */
ProductVariantType.prototype.variantType = undefined;

/**
 * @member {Number} variantTypeId
 */
ProductVariantType.prototype.variantTypeId = undefined;

