/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Entity} from './Entity';

/**
 * The ProductAddOn model module.
 * @module model/ProductAddOn
 * @version v1
 */
export class ProductAddOn extends Entity {
  /**
   * Constructs a new <code>ProductAddOn</code>.
   * @alias module:model/ProductAddOn
   * @class
   * @extends module:model/Entity
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>ProductAddOn</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductAddOn} obj Optional instance to populate.
   * @return {module:model/ProductAddOn} The populated <code>ProductAddOn</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductAddOn();
      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('product'))
        obj.product = ApiClient.convertToType(data['product'], Object);
      if (data.hasOwnProperty('productId'))
        obj.productId = ApiClient.convertToType(data['productId'], 'Number');
      if (data.hasOwnProperty('addOn'))
        obj.addOn = ApiClient.convertToType(data['addOn'], Object);
      if (data.hasOwnProperty('addOnId'))
        obj.addOnId = ApiClient.convertToType(data['addOnId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Object} product
 */
ProductAddOn.prototype.product = undefined;

/**
 * @member {Number} productId
 */
ProductAddOn.prototype.productId = undefined;

/**
 * @member {Object} addOn
 */
ProductAddOn.prototype.addOn = undefined;

/**
 * @member {Number} addOnId
 */
ProductAddOn.prototype.addOnId = undefined;

