/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Product} from './Product';
import {Store} from './Store';

/**
 * The SearchResults model module.
 * @module model/SearchResults
 * @version v1
 */
export class SearchResults {
  /**
   * Constructs a new <code>SearchResults</code>.
   * @alias module:model/SearchResults
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SearchResults</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchResults} obj Optional instance to populate.
   * @return {module:model/SearchResults} The populated <code>SearchResults</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SearchResults();
      if (data.hasOwnProperty('stores'))
        obj.stores = ApiClient.convertToType(data['stores'], [Store]);
      if (data.hasOwnProperty('products'))
        obj.products = ApiClient.convertToType(data['products'], [Product]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Store>} stores
 */
SearchResults.prototype.stores = undefined;

/**
 * @member {Array.<module:model/Product>} products
 */
SearchResults.prototype.products = undefined;

