/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Entity} from './Entity';
import {ShipmentStatus} from './ShipmentStatus';
import {ShipmentType} from './ShipmentType';
import {ShippingMethod} from './ShippingMethod';

/**
 * The Shipment model module.
 * @module model/Shipment
 * @version v1
 */
export class Shipment extends Entity {
  /**
   * Constructs a new <code>Shipment</code>.
   * @alias module:model/Shipment
   * @class
   * @extends module:model/Entity
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>Shipment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Shipment} obj Optional instance to populate.
   * @return {module:model/Shipment} The populated <code>Shipment</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Shipment();
      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('orderId'))
        obj.orderId = ApiClient.convertToType(data['orderId'], 'Number');
      if (data.hasOwnProperty('order'))
        obj.order = ApiClient.convertToType(data['order'], Object);
      if (data.hasOwnProperty('trackingNumber'))
        obj.trackingNumber = ApiClient.convertToType(data['trackingNumber'], 'String');
      if (data.hasOwnProperty('totalWeight'))
        obj.totalWeight = ApiClient.convertToType(data['totalWeight'], 'Number');
      if (data.hasOwnProperty('shippedDate'))
        obj.shippedDate = ApiClient.convertToType(data['shippedDate'], 'Date');
      if (data.hasOwnProperty('deliveredDate'))
        obj.deliveredDate = ApiClient.convertToType(data['deliveredDate'], 'Date');
      if (data.hasOwnProperty('shippingMethodId'))
        obj.shippingMethodId = ApiClient.convertToType(data['shippingMethodId'], 'String');
      if (data.hasOwnProperty('shippingMethod'))
        obj.shippingMethod = ShippingMethod.constructFromObject(data['shippingMethod']);
      if (data.hasOwnProperty('storeId'))
        obj.storeId = ApiClient.convertToType(data['storeId'], 'Number');
      if (data.hasOwnProperty('store'))
        obj.store = ApiClient.convertToType(data['store'], Object);
      if (data.hasOwnProperty('status'))
        obj.status = ShipmentStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('type'))
        obj.type = ShipmentType.constructFromObject(data['type']);
      if (data.hasOwnProperty('service'))
        obj.service = ApiClient.convertToType(data['service'], 'String');
    }
    return obj;
  }
}

/**
 * The ID of the Order this Shipment relates to
 * @member {Number} orderId
 */
Shipment.prototype.orderId = undefined;

/**
 * @member {Object} order
 */
Shipment.prototype.order = undefined;

/**
 * Payment Method Tracking Number
 * @member {String} trackingNumber
 */
Shipment.prototype.trackingNumber = undefined;

/**
 * Total Shipment Weight
 * @member {Number} totalWeight
 */
Shipment.prototype.totalWeight = undefined;

/**
 * The Date/Time the shipment left the Merchant
 * @member {Date} shippedDate
 */
Shipment.prototype.shippedDate = undefined;

/**
 * The Date/Time the Shipment was Delivered
 * @member {Date} deliveredDate
 */
Shipment.prototype.deliveredDate = undefined;

/**
 * The ID of the Shipping methid
 * @member {String} shippingMethodId
 */
Shipment.prototype.shippingMethodId = undefined;

/**
 * @member {module:model/ShippingMethod} shippingMethod
 */
Shipment.prototype.shippingMethod = undefined;

/**
 * @member {Number} storeId
 */
Shipment.prototype.storeId = undefined;

/**
 * @member {Object} store
 */
Shipment.prototype.store = undefined;

/**
 * @member {module:model/ShipmentStatus} status
 */
Shipment.prototype.status = undefined;

/**
 * @member {module:model/ShipmentType} type
 */
Shipment.prototype.type = undefined;

/**
 * @member {String} service
 */
Shipment.prototype.service = undefined;

