/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ShippingMethod} from './ShippingMethod';

/**
 * The ShipmentQuote model module.
 * @module model/ShipmentQuote
 * @version v1
 */
export class ShipmentQuote {
  /**
   * Constructs a new <code>ShipmentQuote</code>.
   * @alias module:model/ShipmentQuote
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ShipmentQuote</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ShipmentQuote} obj Optional instance to populate.
   * @return {module:model/ShipmentQuote} The populated <code>ShipmentQuote</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ShipmentQuote();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], 'Number');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
      if (data.hasOwnProperty('isInCoverage'))
        obj.isInCoverage = ApiClient.convertToType(data['isInCoverage'], 'Boolean');
      if (data.hasOwnProperty('hasQuote'))
        obj.hasQuote = ApiClient.convertToType(data['hasQuote'], 'Boolean');
      if (data.hasOwnProperty('shippingMethod'))
        obj.shippingMethod = ShippingMethod.constructFromObject(data['shippingMethod']);
      if (data.hasOwnProperty('service'))
        obj.service = ApiClient.convertToType(data['service'], 'String');
      if (data.hasOwnProperty('coverageAreaPriceId'))
        obj.coverageAreaPriceId = ApiClient.convertToType(data['coverageAreaPriceId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
ShipmentQuote.prototype.name = undefined;

/**
 * @member {Number} price
 */
ShipmentQuote.prototype.price = undefined;

/**
 * @member {String} currency
 */
ShipmentQuote.prototype.currency = undefined;

/**
 * @member {Boolean} isInCoverage
 */
ShipmentQuote.prototype.isInCoverage = undefined;

/**
 * @member {Boolean} hasQuote
 */
ShipmentQuote.prototype.hasQuote = undefined;

/**
 * @member {module:model/ShippingMethod} shippingMethod
 */
ShipmentQuote.prototype.shippingMethod = undefined;

/**
 * @member {String} service
 */
ShipmentQuote.prototype.service = undefined;

/**
 * @member {Number} coverageAreaPriceId
 */
ShipmentQuote.prototype.coverageAreaPriceId = undefined;

