/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Entity} from './Entity';

/**
 * The SpecialCategoryProduct model module.
 * @module model/SpecialCategoryProduct
 * @version v1
 */
export class SpecialCategoryProduct extends Entity {
  /**
   * Constructs a new <code>SpecialCategoryProduct</code>.
   * @alias module:model/SpecialCategoryProduct
   * @class
   * @extends module:model/Entity
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>SpecialCategoryProduct</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SpecialCategoryProduct} obj Optional instance to populate.
   * @return {module:model/SpecialCategoryProduct} The populated <code>SpecialCategoryProduct</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SpecialCategoryProduct();
      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('productId'))
        obj.productId = ApiClient.convertToType(data['productId'], 'Number');
      if (data.hasOwnProperty('product'))
        obj.product = ApiClient.convertToType(data['product'], Object);
      if (data.hasOwnProperty('specialCategory'))
        obj.specialCategory = ApiClient.convertToType(data['specialCategory'], Object);
      if (data.hasOwnProperty('specialCategoryId'))
        obj.specialCategoryId = ApiClient.convertToType(data['specialCategoryId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} productId
 */
SpecialCategoryProduct.prototype.productId = undefined;

/**
 * @member {Object} product
 */
SpecialCategoryProduct.prototype.product = undefined;

/**
 * @member {Object} specialCategory
 */
SpecialCategoryProduct.prototype.specialCategory = undefined;

/**
 * @member {Number} specialCategoryId
 */
SpecialCategoryProduct.prototype.specialCategoryId = undefined;

