/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class SuspiciousActivityReportOutcome.
 * @enum {Number}
 * @readonly
 */
const SuspiciousActivityReportOutcome = {
  /**
   * value: 0
   * @const
   */
  _0: 0,

  /**
   * value: 1
   * @const
   */
  _1: 1,

  /**
   * value: 2
   * @const
   */
  _2: 2,

  /**
   * value: 3
   * @const
   */
  _3: 3,

  /**
   * value: 4
   * @const
   */
  _4: 4,

  /**
   * value: 5
   * @const
   */
  _5: 5,

  /**
   * value: 6
   * @const
   */
  _6: 6,

  /**
   * value: 7
   * @const
   */
  _7: 7,

  /**
   * value: 8
   * @const
   */
  _8: 8,

  /**
   * Returns a <code>SuspiciousActivityReportOutcome</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/SuspiciousActivityReportOutcome} The enum <code>SuspiciousActivityReportOutcome</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {SuspiciousActivityReportOutcome};