/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Entity} from './Entity';

/**
 * The TenantShippingMethodServiceType model module.
 * @module model/TenantShippingMethodServiceType
 * @version v1
 */
export class TenantShippingMethodServiceType extends Entity {
  /**
   * Constructs a new <code>TenantShippingMethodServiceType</code>.
   * @alias module:model/TenantShippingMethodServiceType
   * @class
   * @extends module:model/Entity
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>TenantShippingMethodServiceType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TenantShippingMethodServiceType} obj Optional instance to populate.
   * @return {module:model/TenantShippingMethodServiceType} The populated <code>TenantShippingMethodServiceType</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TenantShippingMethodServiceType();
      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('tenantShippingMethodId'))
        obj.tenantShippingMethodId = ApiClient.convertToType(data['tenantShippingMethodId'], 'Number');
      if (data.hasOwnProperty('tenantShippingMethod'))
        obj.tenantShippingMethod = ApiClient.convertToType(data['tenantShippingMethod'], Object);
      if (data.hasOwnProperty('enforceStartEndTimes'))
        obj.enforceStartEndTimes = ApiClient.convertToType(data['enforceStartEndTimes'], 'Boolean');
      if (data.hasOwnProperty('directDeliveryEnabled'))
        obj.directDeliveryEnabled = ApiClient.convertToType(data['directDeliveryEnabled'], 'Boolean');
      if (data.hasOwnProperty('startHour'))
        obj.startHour = ApiClient.convertToType(data['startHour'], 'Number');
      if (data.hasOwnProperty('startMinute'))
        obj.startMinute = ApiClient.convertToType(data['startMinute'], 'Number');
      if (data.hasOwnProperty('endHour'))
        obj.endHour = ApiClient.convertToType(data['endHour'], 'Number');
      if (data.hasOwnProperty('endMinute'))
        obj.endMinute = ApiClient.convertToType(data['endMinute'], 'Number');
      if (data.hasOwnProperty('shippingMethodId'))
        obj.shippingMethodId = ApiClient.convertToType(data['shippingMethodId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} tenantShippingMethodId
 */
TenantShippingMethodServiceType.prototype.tenantShippingMethodId = undefined;

/**
 * @member {Object} tenantShippingMethod
 */
TenantShippingMethodServiceType.prototype.tenantShippingMethod = undefined;

/**
 * Determines if the Start/End times will be enforced
 * @member {Boolean} enforceStartEndTimes
 */
TenantShippingMethodServiceType.prototype.enforceStartEndTimes = undefined;

/**
 * Determines if the Shipping Method supports Direct Delivery
 * @member {Boolean} directDeliveryEnabled
 */
TenantShippingMethodServiceType.prototype.directDeliveryEnabled = undefined;

/**
 * The hour the Shipping Method starts delivery service 
 * @member {Number} startHour
 */
TenantShippingMethodServiceType.prototype.startHour = undefined;

/**
 * The minute the Shipping Method starts delivery service
 * @member {Number} startMinute
 */
TenantShippingMethodServiceType.prototype.startMinute = undefined;

/**
 * The hour the Shipping Method ends the delivery service
 * @member {Number} endHour
 */
TenantShippingMethodServiceType.prototype.endHour = undefined;

/**
 * The hour the Shipping Method ends the delivery service
 * @member {Number} endMinute
 */
TenantShippingMethodServiceType.prototype.endMinute = undefined;

/**
 * @member {String} shippingMethodId
 */
TenantShippingMethodServiceType.prototype.shippingMethodId = undefined;

