/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Entity} from './Entity';
import {TenantShippingMethodServiceType} from './TenantShippingMethodServiceType';

/**
 * The TenantShippingMethod model module.
 * @module model/TenantShippingMethod
 * @version v1
 */
export class TenantShippingMethod extends Entity {
  /**
   * Constructs a new <code>TenantShippingMethod</code>.
   * @alias module:model/TenantShippingMethod
   * @class
   * @extends module:model/Entity
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>TenantShippingMethod</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TenantShippingMethod} obj Optional instance to populate.
   * @return {module:model/TenantShippingMethod} The populated <code>TenantShippingMethod</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TenantShippingMethod();
      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('shippingMethod'))
        obj.shippingMethod = ApiClient.convertToType(data['shippingMethod'], Object);
      if (data.hasOwnProperty('tenantShippingMethodServiceTypes'))
        obj.tenantShippingMethodServiceTypes = ApiClient.convertToType(data['tenantShippingMethodServiceTypes'], [TenantShippingMethodServiceType]);
    }
    return obj;
  }
}

/**
 * The Shipping Method available for the Tenant
 * @member {Object} shippingMethod
 */
TenantShippingMethod.prototype.shippingMethod = undefined;

/**
 * @member {Array.<module:model/TenantShippingMethodServiceType>} tenantShippingMethodServiceTypes
 */
TenantShippingMethod.prototype.tenantShippingMethodServiceTypes = undefined;

