/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Entity} from './Entity';

/**
 * The TenantPaymentMethod model module.
 * @module model/TenantPaymentMethod
 * @version v1
 */
export class TenantPaymentMethod extends Entity {
  /**
   * Constructs a new <code>TenantPaymentMethod</code>.
   * @alias module:model/TenantPaymentMethod
   * @class
   * @extends module:model/Entity
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>TenantPaymentMethod</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TenantPaymentMethod} obj Optional instance to populate.
   * @return {module:model/TenantPaymentMethod} The populated <code>TenantPaymentMethod</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TenantPaymentMethod();
      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('paymentMethod'))
        obj.paymentMethod = ApiClient.convertToType(data['paymentMethod'], Object);
      if (data.hasOwnProperty('enabled'))
        obj.enabled = ApiClient.convertToType(data['enabled'], 'Boolean');
      if (data.hasOwnProperty('transactionFeePercentage'))
        obj.transactionFeePercentage = ApiClient.convertToType(data['transactionFeePercentage'], 'Number');
    }
    return obj;
  }
}

/**
 * The ID of the Payment Method available for the Tenant
 * @member {Object} paymentMethod
 */
TenantPaymentMethod.prototype.paymentMethod = undefined;

/**
 * @member {Boolean} enabled
 */
TenantPaymentMethod.prototype.enabled = undefined;

/**
 * @member {Number} transactionFeePercentage
 */
TenantPaymentMethod.prototype.transactionFeePercentage = undefined;

