/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Entity} from './Entity';

/**
 * The TenantCurrency model module.
 * @module model/TenantCurrency
 * @version v1
 */
export class TenantCurrency extends Entity {
  /**
   * Constructs a new <code>TenantCurrency</code>.
   * @alias module:model/TenantCurrency
   * @class
   * @extends module:model/Entity
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>TenantCurrency</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TenantCurrency} obj Optional instance to populate.
   * @return {module:model/TenantCurrency} The populated <code>TenantCurrency</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TenantCurrency();
      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('currencyId'))
        obj.currencyId = ApiClient.convertToType(data['currencyId'], 'Number');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], Object);
      if (data.hasOwnProperty('isDefault'))
        obj.isDefault = ApiClient.convertToType(data['isDefault'], 'Boolean');
    }
    return obj;
  }
}

/**
 * The ID of the Currency
 * @member {Number} currencyId
 */
TenantCurrency.prototype.currencyId = undefined;

/**
 * @member {Object} currency
 */
TenantCurrency.prototype.currency = undefined;

/**
 * @member {Boolean} isDefault
 */
TenantCurrency.prototype.isDefault = undefined;

