/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Entity} from './Entity';

/**
 * The TenantLanguage model module.
 * @module model/TenantLanguage
 * @version v1
 */
export class TenantLanguage extends Entity {
  /**
   * Constructs a new <code>TenantLanguage</code>.
   * @alias module:model/TenantLanguage
   * @class
   * @extends module:model/Entity
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>TenantLanguage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TenantLanguage} obj Optional instance to populate.
   * @return {module:model/TenantLanguage} The populated <code>TenantLanguage</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TenantLanguage();
      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('languageId'))
        obj.languageId = ApiClient.convertToType(data['languageId'], 'Number');
      if (data.hasOwnProperty('language'))
        obj.language = ApiClient.convertToType(data['language'], Object);
      if (data.hasOwnProperty('isDefault'))
        obj.isDefault = ApiClient.convertToType(data['isDefault'], 'Boolean');
    }
    return obj;
  }
}

/**
 * The ID of the Language used by the Tenant
 * @member {Number} languageId
 */
TenantLanguage.prototype.languageId = undefined;

/**
 * @member {Object} language
 */
TenantLanguage.prototype.language = undefined;

/**
 * @member {Boolean} isDefault
 */
TenantLanguage.prototype.isDefault = undefined;

