/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UserProfile model module.
 * @module model/UserProfile
 * @version v1
 */
export class UserProfile {
  /**
   * Constructs a new <code>UserProfile</code>.
   * @alias module:model/UserProfile
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UserProfile</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserProfile} obj Optional instance to populate.
   * @return {module:model/UserProfile} The populated <code>UserProfile</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserProfile();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('latitude'))
        obj.latitude = ApiClient.convertToType(data['latitude'], 'Number');
      if (data.hasOwnProperty('longitude'))
        obj.longitude = ApiClient.convertToType(data['longitude'], 'Number');
      if (data.hasOwnProperty('phoneNumber'))
        obj.phoneNumber = ApiClient.convertToType(data['phoneNumber'], 'String');
      if (data.hasOwnProperty('firstName'))
        obj.firstName = ApiClient.convertToType(data['firstName'], 'String');
      if (data.hasOwnProperty('lastName'))
        obj.lastName = ApiClient.convertToType(data['lastName'], 'String');
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('userName'))
        obj.userName = ApiClient.convertToType(data['userName'], 'String');
      if (data.hasOwnProperty('language'))
        obj.language = ApiClient.convertToType(data['language'], 'String');
      if (data.hasOwnProperty('defaultAddressId'))
        obj.defaultAddressId = ApiClient.convertToType(data['defaultAddressId'], 'Number');
      if (data.hasOwnProperty('twoFactorEnabled'))
        obj.twoFactorEnabled = ApiClient.convertToType(data['twoFactorEnabled'], 'Boolean');
      if (data.hasOwnProperty('supportPinChanged'))
        obj.supportPinChanged = ApiClient.convertToType(data['supportPinChanged'], 'Date');
      if (data.hasOwnProperty('supportPin'))
        obj.supportPin = ApiClient.convertToType(data['supportPin'], 'String');
      if (data.hasOwnProperty('emailConfirmed'))
        obj.emailConfirmed = ApiClient.convertToType(data['emailConfirmed'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
UserProfile.prototype.id = undefined;

/**
 * @member {String} email
 */
UserProfile.prototype.email = undefined;

/**
 * @member {Number} latitude
 */
UserProfile.prototype.latitude = undefined;

/**
 * @member {Number} longitude
 */
UserProfile.prototype.longitude = undefined;

/**
 * @member {String} phoneNumber
 */
UserProfile.prototype.phoneNumber = undefined;

/**
 * @member {String} firstName
 */
UserProfile.prototype.firstName = undefined;

/**
 * @member {String} lastName
 */
UserProfile.prototype.lastName = undefined;

/**
 * @member {Date} created
 */
UserProfile.prototype.created = undefined;

/**
 * @member {String} userName
 */
UserProfile.prototype.userName = undefined;

/**
 * @member {String} language
 */
UserProfile.prototype.language = undefined;

/**
 * @member {Number} defaultAddressId
 */
UserProfile.prototype.defaultAddressId = undefined;

/**
 * @member {Boolean} twoFactorEnabled
 */
UserProfile.prototype.twoFactorEnabled = undefined;

/**
 * @member {Date} supportPinChanged
 */
UserProfile.prototype.supportPinChanged = undefined;

/**
 * @member {String} supportPin
 */
UserProfile.prototype.supportPin = undefined;

/**
 * @member {Boolean} emailConfirmed
 */
UserProfile.prototype.emailConfirmed = undefined;

