/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Entity} from './Entity';
import {SyncPlatform} from './SyncPlatform';

/**
 * The VariantType model module.
 * @module model/VariantType
 * @version v1
 */
export class VariantType extends Entity {
  /**
   * Constructs a new <code>VariantType</code>.
   * @alias module:model/VariantType
   * @class
   * @extends module:model/Entity
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>VariantType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VariantType} obj Optional instance to populate.
   * @return {module:model/VariantType} The populated <code>VariantType</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new VariantType();
      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('storeId'))
        obj.storeId = ApiClient.convertToType(data['storeId'], 'Number');
      if (data.hasOwnProperty('store'))
        obj.store = ApiClient.convertToType(data['store'], Object);
      if (data.hasOwnProperty('group'))
        obj.group = ApiClient.convertToType(data['group'], 'String');
      if (data.hasOwnProperty('syncId'))
        obj.syncId = ApiClient.convertToType(data['syncId'], 'String');
      if (data.hasOwnProperty('lastSynced'))
        obj.lastSynced = ApiClient.convertToType(data['lastSynced'], 'Date');
      if (data.hasOwnProperty('syncPlatform'))
        obj.syncPlatform = SyncPlatform.constructFromObject(data['syncPlatform']);
    }
    return obj;
  }
}

/**
 * The ID of the Store this Variant Type is from
 * @member {Number} storeId
 */
VariantType.prototype.storeId = undefined;

/**
 * The Store this Variant Type is from
 * @member {Object} store
 */
VariantType.prototype.store = undefined;

/**
 * The name of the Group this variant type is for. This name is used to distinctly group variants together.
 * @member {String} group
 */
VariantType.prototype.group = undefined;

/**
 * @member {String} syncId
 */
VariantType.prototype.syncId = undefined;

/**
 * @member {Date} lastSynced
 */
VariantType.prototype.lastSynced = undefined;

/**
 * @member {module:model/SyncPlatform} syncPlatform
 */
VariantType.prototype.syncPlatform = undefined;

