/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Entity} from './Entity';
import {VerificationDocument} from './VerificationDocument';
import {VerificationStatus} from './VerificationStatus';
import {VerificationType} from './VerificationType';

/**
 * The Verification model module.
 * @module model/Verification
 * @version v1
 */
export class Verification extends Entity {
  /**
   * Constructs a new <code>Verification</code>.
   * @alias module:model/Verification
   * @class
   * @extends module:model/Entity
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>Verification</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Verification} obj Optional instance to populate.
   * @return {module:model/Verification} The populated <code>Verification</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Verification();
      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('documents'))
        obj.documents = ApiClient.convertToType(data['documents'], [VerificationDocument]);
      if (data.hasOwnProperty('status'))
        obj.status = VerificationStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('type'))
        obj.type = VerificationType.constructFromObject(data['type']);
      if (data.hasOwnProperty('storeId'))
        obj.storeId = ApiClient.convertToType(data['storeId'], 'Number');
      if (data.hasOwnProperty('isBusiness'))
        obj.isBusiness = ApiClient.convertToType(data['isBusiness'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/VerificationDocument>} documents
 */
Verification.prototype.documents = undefined;

/**
 * @member {module:model/VerificationStatus} status
 */
Verification.prototype.status = undefined;

/**
 * @member {module:model/VerificationType} type
 */
Verification.prototype.type = undefined;

/**
 * @member {Number} storeId
 */
Verification.prototype.storeId = undefined;

/**
 * @member {Boolean} isBusiness
 */
Verification.prototype.isBusiness = undefined;

