/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Entity} from './Entity';
import {VerificationDocumentType} from './VerificationDocumentType';
import {VerificationStatus} from './VerificationStatus';

/**
 * The VerificationDocument model module.
 * @module model/VerificationDocument
 * @version v1
 */
export class VerificationDocument extends Entity {
  /**
   * Constructs a new <code>VerificationDocument</code>.
   * @alias module:model/VerificationDocument
   * @class
   * @extends module:model/Entity
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>VerificationDocument</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VerificationDocument} obj Optional instance to populate.
   * @return {module:model/VerificationDocument} The populated <code>VerificationDocument</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new VerificationDocument();
      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], 'Blob');
      if (data.hasOwnProperty('dataContentType'))
        obj.dataContentType = ApiClient.convertToType(data['dataContentType'], 'String');
      if (data.hasOwnProperty('verifierId'))
        obj.verifierId = ApiClient.convertToType(data['verifierId'], 'String');
      if (data.hasOwnProperty('verifiedAt'))
        obj.verifiedAt = ApiClient.convertToType(data['verifiedAt'], 'Date');
      if (data.hasOwnProperty('verificationId'))
        obj.verificationId = ApiClient.convertToType(data['verificationId'], 'Number');
      if (data.hasOwnProperty('verification'))
        obj.verification = ApiClient.convertToType(data['verification'], Object);
      if (data.hasOwnProperty('status'))
        obj.status = VerificationStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('documentType'))
        obj.documentType = VerificationDocumentType.constructFromObject(data['documentType']);
    }
    return obj;
  }
}

/**
 * @member {Blob} data
 */
VerificationDocument.prototype.data = undefined;

/**
 * @member {String} dataContentType
 */
VerificationDocument.prototype.dataContentType = undefined;

/**
 * @member {String} verifierId
 */
VerificationDocument.prototype.verifierId = undefined;

/**
 * @member {Date} verifiedAt
 */
VerificationDocument.prototype.verifiedAt = undefined;

/**
 * @member {Number} verificationId
 */
VerificationDocument.prototype.verificationId = undefined;

/**
 * @member {Object} verification
 */
VerificationDocument.prototype.verification = undefined;

/**
 * @member {module:model/VerificationStatus} status
 */
VerificationDocument.prototype.status = undefined;

/**
 * @member {module:model/VerificationDocumentType} documentType
 */
VerificationDocument.prototype.documentType = undefined;

