/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Entity} from './Entity';
import {WishlistItem} from './WishlistItem';

/**
 * The Wishlist model module.
 * @module model/Wishlist
 * @version v1
 */
export class Wishlist extends Entity {
  /**
   * Constructs a new <code>Wishlist</code>.
   * @alias module:model/Wishlist
   * @class
   * @extends module:model/Entity
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>Wishlist</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Wishlist} obj Optional instance to populate.
   * @return {module:model/Wishlist} The populated <code>Wishlist</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Wishlist();
      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('isPublic'))
        obj.isPublic = ApiClient.convertToType(data['isPublic'], 'Boolean');
      if (data.hasOwnProperty('items'))
        obj.items = ApiClient.convertToType(data['items'], [WishlistItem]);
    }
    return obj;
  }
}

/**
 * If this is true the wishlist will be accessible to the public
 * @member {Boolean} isPublic
 */
Wishlist.prototype.isPublic = undefined;

/**
 * The items contained within the wishlist
 * @member {Array.<module:model/WishlistItem>} items
 */
Wishlist.prototype.items = undefined;

