/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Entity} from './Entity';

/**
 * The WishlistItem model module.
 * @module model/WishlistItem
 * @version v1
 */
export class WishlistItem extends Entity {
  /**
   * Constructs a new <code>WishlistItem</code>.
   * @alias module:model/WishlistItem
   * @class
   * @extends module:model/Entity
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>WishlistItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WishlistItem} obj Optional instance to populate.
   * @return {module:model/WishlistItem} The populated <code>WishlistItem</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WishlistItem();
      Entity.constructFromObject(data, obj);
      if (data.hasOwnProperty('productId'))
        obj.productId = ApiClient.convertToType(data['productId'], 'Number');
      if (data.hasOwnProperty('product'))
        obj.product = ApiClient.convertToType(data['product'], Object);
      if (data.hasOwnProperty('storeId'))
        obj.storeId = ApiClient.convertToType(data['storeId'], 'Number');
      if (data.hasOwnProperty('store'))
        obj.store = ApiClient.convertToType(data['store'], Object);
      if (data.hasOwnProperty('wishlistId'))
        obj.wishlistId = ApiClient.convertToType(data['wishlistId'], 'Number');
      if (data.hasOwnProperty('wishlist'))
        obj.wishlist = ApiClient.convertToType(data['wishlist'], Object);
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'Number');
    }
    return obj;
  }
}

/**
 * The ID of the Product for the Cart Item
 * @member {Number} productId
 */
WishlistItem.prototype.productId = undefined;

/**
 * @member {Object} product
 */
WishlistItem.prototype.product = undefined;

/**
 * The ID of the Store the wishlist item is from
 * @member {Number} storeId
 */
WishlistItem.prototype.storeId = undefined;

/**
 * The Store the wishlist item is from
 * @member {Object} store
 */
WishlistItem.prototype.store = undefined;

/**
 * The ID of the Wishlist this item belongs to. If this is null, the item is part of the users default wishlist
 * @member {Number} wishlistId
 */
WishlistItem.prototype.wishlistId = undefined;

/**
 * @member {Object} wishlist
 */
WishlistItem.prototype.wishlist = undefined;

/**
 * The quantity of items
 * @member {Number} quantity
 */
WishlistItem.prototype.quantity = undefined;

