/*
 * Hangme API
 * Hangme offers services for our merchant, consumer, driver and partner applications. How you can interact with these services is documented here.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {ProblemDetails} from '../model/ProblemDetails';
import {ShipmentQuote} from '../model/ShipmentQuote';

/**
* Shipping service.
* @module api/ShippingApi
* @version v1
*/
export class ShippingApi {

    /**
    * Constructs a new ShippingApi. 
    * @alias module:api/ShippingApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the getDeliveryQuotesByAddress operation.
     * @callback moduleapi/ShippingApi~getDeliveryQuotesByAddressCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ShipmentQuote>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Shipping Estimates for Address
     * Gets an estimated delivery costs for an order based on Address
     * @param {Object} opts Optional parameters
     * @param {Number} opts.storeId 
     * @param {Number} opts.addressId 
     * @param {module:api/ShippingApi~getDeliveryQuotesByAddressCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getDeliveryQuotesByAddress(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'storeId': opts['storeId'],'addressId': opts['addressId']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [ShipmentQuote];

      return this.apiClient.callApi(
        '/api/shipping/quotes-by-address', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}